### ISSUE TITLE
Feature request: allow ignoring certain folders

### ISSUE THREAD

**Issue by tesselode** [bjornbytes/cargo#4]
Right now I'm working on a mini game framework kind of thing, and I have a certain way I want to load assets from certain folders. It would be nice if I could tell cargo to not bother loading those folders, since I'm doing it myself. It's nothing critical, but it would be nice to avoid wasting resources.

**Comment by bjornbytes** [comment]
Cargo will effectively ignore folders or assets that are never accessed.  So if you never have `assets.ignored_dir.asset` in your code, `ignored_dir.asset` will never be loaded.

With that said, the ability to ignore certain assets or folders could come in handy in some situations.  It would probably take the form of a table of patterns (similar to the current `processors` table).

**Comment by tesselode** [comment]
Fair enough, there really isn't any overhead if you never access the assets.
